---
unbound_package_name: 'unbound'
unbound_package_state: 'present'

unbound_service_name: 'unbound'
unbound_service_state: 'started'
unbound_service_enabled: yes

unbound_interfaces:
  - 127.0.0.1
  - ::1

unbound_access_control:
  - 127.0.0.1 allow
  - ::1 allow

unbound_forward_zones:
  - name: .
    forward_addr:
      - 2606:4700:4700::1111
      - 2001:4860:4860::8888
      - 2620:fe::fe
      - 2606:4700:4700::1001
      - 2001:4860:4860::8844
      - 2620:fe::9
      - 1.1.1.1
      - 8.8.8.8
      - 9.9.9.9
      - 1.0.0.1
      - 8.8.4.4
      - 149.112.112.112

# vim:ft=yaml.ansible:
