---
certbot_package_name: certbot
certbot_package_state: present

certbot_service_name: certbot.service

certbot_timer_name: certbot.timer
certbot_timer_state: started
certbot_timer_enabled: yes

certbot_cron_user: root
certbot_cron_file_path: /etc/cron.d/certbot
certbot_cron_env:
  path: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
  shell: /bin/sh
certbot_cron_command: test -x /usr/bin/certbot -a \! -d /run/systemd/system && perl -e 'sleep int(rand(43200))' && certbot -q renew
cerbot_cron_hour: "*/12"
cerbot_cron_minute: "0"

certbot_system_timer_on_calender: "*-*-* 00,12:00:00"
certbot_system_timer_randomized_delay_sec: 43200
