---
- name: restart systemd-networkd
  service:
    name: "{{ _network_systemd_networkd_service_name }}"
    state: restarted
  when:  _network_systemd_networkd_enabled

- name: restart ifupdown
  service:
    name: "{{ _network_ifupdown_service_name }}"
    state: restarted
  when:  _network_ifupdown_enabled

- name: netplan apply
  command: netplan apply
  when:  _network_netplan_enabled

- name: restart systemd-resolved
  service:
    name: "{{ _network_systemd_resolved_service_name }}"
    state: restarted
  when: _network_systemd_resolved_available

# vim:ft=yaml.ansible:
