---
- name: gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"

- name: gather virtualization specific variables
  include_vars: "{{ item }}"
  with_first_found:
    "{{ ansible_virtualization_type }}.yaml"

- name: run virtualization specific tasks
  include: "{{ item }}"
  with_first_found:
    "{{ ansible_virtualization_type }}.yaml"
