---
- name: add grafana apt key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: configure apt repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    filename: influxdb
    update_cache: yes
    state: present
