---
- name: create grafana-server.service.d
  file:
    path: /etc/systemd/system/grafana-server.service.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: configure systemd override
  copy:
    src: Ubuntu-18-override.conf
    dest: /etc/systemd/system/grafana-server.service.d/10-override.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - grafana daemon-reload
    - restart grafana
