---
- name: reload nomad
  service:
    name: "{{ nomad_service_name }}"
    state: reloaded
  when: nomad_service_enabled

- name: restart nomad
  service:
    name: "{{ nomad_service_name }}"
    state: restarted
  when: nomad_service_enabled
