---
- hosts: all
  become: true
  roles:
    - common
    - network
    - util
    - sudo
    - hostsfile
    - certs
    - rsyslog
    - users
    - dns
    - firewall
    - openssh
    - wireguard
    - chrony
    - unattended-upgrades
    - postfix
    - restic
    - node_exporter
    - blackbox_exporter
    - mtail
    - supervisor
- hosts: minecraft_servers
  become: true
  roles:
    - minecraft
- hosts: jump_servers
  become: true
  roles:
    - go
    - dl
- hosts: git_servers
  become: true
  roles:
    - nginx
    - certbot
    - gitea
- hosts: stats_servers
  become: true
  roles:
    - nginx
    - certbot
    - grafana
- hosts: monitor_servers
  become: true
  roles:
    - nginx
    - role: prometheus
      tags:
        - prometheus
        - monitoring
    - alertmanager
    - blackbox_exporter
    - pushgateway
    - role: karma
      tags:
        - monitoring
    - role: kthxbye
      tags:
        - monitoring
    - role: thanos
      tags:
        - thanos
        - monitoring

# vim:ft=yaml.ansible:
