---
rsyslog_file_owner: syslog
rsyslog_file_group: adm
rsyslog_file_create_mode: "0644"
rsyslog_dir_create_mode: "0755"
rsyslog_umask: "0022"
rsyslog_priv_drop_to_user: syslog
rsyslog_priv_drop_to_group: syslog

rsyslog_default_rules:
  - "auth,authpriv.*           /var/log/auth.log"
  - "*.*;auth,authpriv.none   -/var/log/syslog"
  - "kern.*                   -/var/log/kern.log"
  - "mail.*                   -/var/log/mail.log"
  - "mail.err                 /var/log/mail.err"
  - "*.emerg                  :omusrmsg:*"

rsyslog_default_log_patterns:
  - auth.log*
  - cron.log*
  - daemon.log*
  - debug*
  - kern.log*
  - lpr.log*
  - mail.err*
  - mail.info*
  - mail.log*
  - mail.warn*
  - messages*
  - syslog*
  - user.log*
