---
minecraft_java_package_name: openjdk-8-jre-headless
minecraft_java_package_state: present

minecraft_service_name: minecraft.service
minecraft_service_state: started
minecraft_service_enabled: yes

minecraft_port: 25565

minecraft_user: minecraft
minecraft_group: minecraft

minecraft_jar_url: https://launcher.mojang.com/v1/objects/c5f6fb23c3876461d46ec380421e42b289789530/server.jar
minecraft_jar_checksum: sha256:2902ed3ff84e4f810a2c0620c6b6df9c3ef8488b272c61274d5eac2433876f39

minecraft_opt_path: /opt/minecraft
minecraft_var_path: /var/opt/minecraft

minecraft_syslog_facility: local5

minecraft_notifier_state: present
