---
minecraft_java_package_name: openjdk-8-jre-headless
minecraft_java_package_state: present

minecraft_service_name: minecraft.service
minecraft_service_state: started
minecraft_service_enabled: yes

minecraft_port: 25565

minecraft_user: minecraft
minecraft_group: minecraft

minecraft_jar_url: https://launcher.mojang.com/v1/objects/e9f105b3c5c7e85c7b445249a93362a22f62442d/server.jar
minecraft_jar_checksum: sha256:e0fe1749263b5ec211b358b598b46e787645bffa8411414f0c812a92bdc70c84

minecraft_opt_path: /opt/minecraft
minecraft_var_path: "{{ minecraft_opt_path }}/var"
minecraft_backup_path: "{{ minecraft_opt_path }}/backup"

minecraft_syslog_facility: local5
