---
minecraft_java_package_name: openjdk-18-jre-headless
minecraft_java_package_state: present

minecraft_service_name: minecraft.service
minecraft_service_state: started
minecraft_service_enabled: yes

minecraft_port: 25565

minecraft_user: minecraft
minecraft_group: minecraft

minecraft_jar_url: https://piston-data.mojang.com/v1/objects/84194a2f286ef7c14ed7ce0090dba59902951553/server.jar
minecraft_jar_checksum: sha256:3af73a9dc5a102e38147946360dd27d4d70bae7055bf91cf2151cd5d121b79e0

minecraft_opt_path: /opt/minecraft
minecraft_var_path: /var/opt/minecraft

minecraft_syslog_facility: local5

minecraft_notifier_state: present

minecraft_config:
  white-list: true
  enforce-whitelist: true
  server-port: 25565
