---
- name: minecraft daemon-reload
  systemd:
    name: "{{ minecraft_service_name }}"
    daemon_reload: yes
    state: restarted

- name: restart minecraft
  service:
    name: "{{ minecraft_service_name }}"
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart minecraft instances
  service:
    name: "minecraft@{{ item.name }}.service"
    state: restarted
  loop: "{{ minecraft_worlds | default([]) }}"
