---
- name: minecraft daemon-reload
  systemd:
    name: "{{ minecraft_service_name }}"
    daemon_reload: yes
    state: restarted

- name: restart minecraft
  service:
    name: "{{ minecraft_service_name }}"
    state: restarted
