---
nginx_package_name: nginx
nginx_package_state: present

nginx_service_name: nginx
nginx_service_state: started
nginx_service_enabled: yes

nginx_etc_path: /etc/nginx
nginx_conf_d_path: "{{ nginx_etc_path }}/conf.d"
nginx_mime_types_path: "{{ nginx_etc_path }}/mime.types"
nginx_var_log_path: /var/log/nginx

nginx_user: nginx
nginx_worker_processes: auto
nginx_error_log: /var/log/nginx/error.log warn
nginx_access_log: /var/log/nginx/access.log main
nginx_pid: /var/run/nginx.pid
nginx_worker_connections: 1024
nginx_default_type: application/octet-stream
nginx_sendfile: "on"
nginx_keepalive_timeout: 65
nginx_gzip: "on"

nginx_root: /var/www/html
nginx_index:
  - index.html
  - index.htm
  #- index.nginx-debian.html;

nginx_acme_challenge_enabled: yes
nginx_acme_challenge_path: /var/www/.acme-challenge

nginx_conf_d: {}
nginx_vhosts: []
