---
gitea_go_arch_map:
  i386: '386'
  x86_64: 'amd64'

gitea_checksums:
  x86_64: sha256:3faa3e97a621c3b9ecba7917fd870c07c3c6c88c8cc7c29ecbf2c7b9802d91b0

gitea_go_arch: "{{ gitea_go_arch_map[ansible_architecture] | default('amd64') }}"
gitea_checksum: "{{ gitea_checksums[ansible_architecture] | default('amd64') }}"

gitea_service_name: gitea.service
gitea_service_state: started
gitea_service_enabled: yes

gitea_version: 1.12.2
gitea_url: "https://dl.gitea.io/gitea/{{ gitea_version }}/gitea-{{ gitea_version }}-linux-{{ gitea_go_arch }}"
gitea_bin_path: /usr/local/bin
gitea_var_path: /var/lib/gitea
gitea_log_path: /var/log/gitea
gitea_etc_path: /etc/gitea
gitea_path: "{{ gitea_bin_path }}/gitea"
gitea_config_path: "{{ gitea_etc_path }}/app.ini"
gitea_systemd_unit_path: /etc/systemd/system/gitea.service
gitea_user: git
gitea_group: git
gitea_shell: /bin/bash
gitea_gecos: Git Version Control
gitea_password: !
gitea_home_path: /home/git
gitea_port: 3001

gitea_config:
  DEFAULT:
    run_mode: prod
  server:
    http_port: "{{ gitea_port }}"
    http_addr: localhost
    domain: "{{ gitea_domain }}"
    root_url: "{{ gitea_ssl_enabled | ternary('https', 'http') }}://{{ gitea_domain }}/"
  oauth2:
    jwt_secret: "{{ vault_gitea_jwt_secret }}"
  security:
    install_lock: true
    internal_token: "{{ vault_gitea_internal_token }}"
  database:
    db_type: sqlite3
  log:
    root_path: /var/log/gitea
    mode: file
    access: file
    macaron: file
    router: file
    redirect_macaron_log: true
  log.console:
    colorize: no
  service:
    disable_registration: yes

gitea_var_tree:
  - "{{ gitea_var_path }}"
  - "{{ gitea_var_path }}/custom"
  - "{{ gitea_var_path }}/data"
  - "{{ gitea_var_path }}/log"
  - "{{ gitea_var_path }}/backup"

gitea_ssl_enabled: yes
gitea_ssl_certificate: "/etc/letsencrypt/live/{{ gitea_domain }}/fullchain.pem"
gitea_ssl_certificate_key: "/etc/letsencrypt/live/{{ gitea_domain }}/privkey.pem"
#gitea_ssl_dhparam: "/etc/letsencrypt/ssl-dhparams.pem"
