{
 "title": "System",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "host", "query": "SHOW TAG VALUES WITH KEY=host" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT  mean(\"used_percent\") FROM \"mem\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory (bytes)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT  mean(\"used\") FROM \"mem\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "query": "SELECT  mean(\"used_percent\") FROM \"swap\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap (bytes)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "query": "SELECT  mean(\"used\") FROM \"swap\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network (rx)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(last(\"bytes_recv\"), 1s) FROM \"net\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network (tx)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(last(\"bytes_recv\"), 1s) FROM \"net\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") AS \"user\", mean(\"usage_system\") AS \"system\", mean(\"usage_nice\") AS \"nice\", mean(\"usage_iowait\") AS \"iowait\", mean(\"usage_irq\") AS \"irq\", mean(\"usage_softirq\") AS \"softirq\", mean(\"usage_steal\") AS \"steal\" FROM \"cpu\" WHERE (\"host\" =~ /^$host$/ AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "nice" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "iowait" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_irq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "irq" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_softirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "softirq" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "steal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT 100 - mean(\"usage_idle\") AS \"usage\" FROM \"cpu\" WHERE (\"host\" =~ /^$host$/ AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "buffered" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "buffered" ], "type": "alias" }
      ],
      [
       { "params": [ "cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cached" ], "type": "alias" }
      ],
      [
       { "params": [ "slab" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "slab" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "shared" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "shared" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage (% bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage (% inodes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"inodes_used\") / last(\"inodes_total\") AS \"used\" FROM \"disk\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "inodes_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage (inodes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"inodes_used\") / last(\"inodes_total\") AS \"used\" FROM \"disk\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "inodes_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "rx" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "rx" ], "type": "alias" }
      ],
      [
       { "params": [ "packets_sent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap Usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "in" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "in" ], "type": "alias" }
      ],
      [
       { "params": [ "out" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "write" ], "type": "alias" }
      ],
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1ms" ], "type": "non_negative_derivative" },
       { "params": [ "write_time" ], "type": "alias" }
      ],
      [
       { "params": [ "read_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1ms" ], "type": "non_negative_derivative" },
       { "params": [ "read_time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "conntrack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "conntrack",
     "select": [
      [
       { "params": [ "ip_conntrack_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netstat",
     "select": [
      [
       { "params": [ "tcp_established" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tcp_established" ], "type": "alias" }
      ],
      [
       { "params": [ "udp_socket" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "udp_socket" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "write" ], "type": "alias" }
      ],
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Entropy Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "select": [
      [
       { "params": [ "entropy_avail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load1" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load5" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load15" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Google DNS Ping",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ],
      [
       { "params": [ "maximum_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ],
      [
       { "params": [ "minimum_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "dns.google" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT mean(\"percent_packet_loss\") AS \"loss\" FROM \"ping\" WHERE (\"url\" = '24.13.205.122') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "loss" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "dns.google" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Gateway Ping (IPv4)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ],
      [
       { "params": [ "maximum_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ],
      [
       { "params": [ "minimum_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "gateway" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT mean(\"percent_packet_loss\") AS \"loss\" FROM \"ping\" WHERE (\"url\" = '24.13.205.122') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "loss" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "dns.google" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Gateway Ping (IPv6)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ],
      [
       { "params": [ "maximum_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ],
      [
       { "params": [ "minimum_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "gateway6" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT mean(\"percent_packet_loss\") AS \"loss\" FROM \"ping\" WHERE (\"url\" = '24.13.205.122') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "loss" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "dns.google" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "VPN Ping (IPv4)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ],
      [
       { "params": [ "maximum_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ],
      [
       { "params": [ "minimum_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "10.255.0.1" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT mean(\"percent_packet_loss\") AS \"loss\" FROM \"ping\" WHERE (\"url\" = '24.13.205.122') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "loss" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "10.255.0.1" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}