---
hostsfile_loopback:
  127.0.0.1:
    - localhost
    - localhost.localdomain
    - localhost4
    - localhost4.localdomain4
  ::1:
    - localhost
    - localhost.localdomain
    - localhost6
    - localhost6.localdomain4
    - ip6-localhost
    - ip6-loopback

hostsfile_self:
  "{{ ansible_default_ipv4.address }}":
    - "{{ ansible_fqdn }}"
  "{{ ansible_default_ipv6.address }}":
    - "{{ ansible_fqdn }}"

hostsfile_routers:
  ff02::1:
    - ip6-allnodes
  ff02::2:
    - ip6-allrouters

hostsfile_hosts: {}
