---
- name: reload docker
  ansible.builtin.service:
    name: "{{ docker_service_name | default('docker') }}"
    state: reloaded

- name: restart docker
  ansible.builtin.service:
    name: "{{ docker_service_name | default('docker') }}"
    state: restarted
  listen:
    - restart nftables
