---
nsd_linode_xfr:
  - "{{ lookup('dig', 'axfr1.linode.com.') }}"
  - "{{ lookup('dig', 'axfr2.linode.com.') }}"
  - "{{ lookup('dig', 'axfr3.linode.com.') }}"
  - "{{ lookup('dig', 'axfr4.linode.com.') }}"
  - "{{ lookup('dig', 'axfr5.linode.com.') }}"
  - "{{ lookup('dig', 'axfr1.linode.com./AAAA') }}"
  - "{{ lookup('dig', 'axfr2.linode.com./AAAA') }}"
  - "{{ lookup('dig', 'axfr3.linode.com./AAAA') }}"
  - "{{ lookup('dig', 'axfr4.linode.com./AAAA') }}"
  - "{{ lookup('dig', 'axfr5.linode.com./AAAA') }}"

nsd_provide_xfr:
  - "{{ lookup('dig', 'axfr1.linode.com.') }} NOKEY"
  - "{{ lookup('dig', 'axfr2.linode.com.') }} NOKEY"
  - "{{ lookup('dig', 'axfr3.linode.com.') }} NOKEY"
  - "{{ lookup('dig', 'axfr4.linode.com.') }} NOKEY"
  - "{{ lookup('dig', 'axfr5.linode.com.') }} NOKEY"
  - "{{ lookup('dig', 'axfr1.linode.com./AAAA') }} NOKEY"
  - "{{ lookup('dig', 'axfr2.linode.com./AAAA') }} NOKEY"
  - "{{ lookup('dig', 'axfr3.linode.com./AAAA') }} NOKEY"
  - "{{ lookup('dig', 'axfr4.linode.com./AAAA') }} NOKEY"
  - "{{ lookup('dig', 'axfr5.linode.com./AAAA') }} NOKEY"

firewall_dns_whitelist: "{{ nsd_linode_xfr }}"
firewall_ipset_dns: "{{ nsd_linode_xfr }}"

nsd_zones:
  - name: cavi.cc
    zonefile: cavi.cc.zone
    provide-xfr: "{{ nsd_provide_xfr }}"
    notify: "{{ nsd_provide_xfr }}"
  - name: kill0.net
    zonefile: kill0.net.zone
    provide-xfr: "{{ nsd_provide_xfr }}"
    notify: "{{ nsd_provide_xfr }}"
  - name: kill0.com
    zonefile: kill0.com.zone
    provide-xfr: "{{ nsd_provide_xfr }}"
    notify: "{{ nsd_provide_xfr }}"
  - name: chill9.com
    zonefile: chill9.com.zone
    provide-xfr: "{{ nsd_provide_xfr }}"
    notify: "{{ nsd_provide_xfr }}"
  - name: chill9.net
    zonefile: chill9.net.zone
    provide-xfr: "{{ nsd_provide_xfr }}"
    notify: "{{ nsd_provide_xfr }}"
  - name: confabulator.net
    zonefile: confabulator.net.zone
    provide-xfr: "{{ nsd_provide_xfr }}"
    notify: "{{ nsd_provide_xfr }}"
  - name: ctrl-v.org
    zonefile: ctrl-v.org.zone
    provide-xfr: "{{ nsd_provide_xfr }}"
    notify: "{{ nsd_provide_xfr }}"
