---
- name: determine if installed
  stat:
    path: "{{ alertmanager_bin_path }}/alertmanager"
  register: st

- name: set alertmanager_installed
  set_fact:
    alertmanager_installed: "{{ st.stat.exists | bool }}"

- block:
  - name: determine latest version
    uri:
      url: https://api.github.com/repos/prometheus/alertmanager/releases/latest
      return_content: true
      body_format: json
    register: _latest_version
    until: _latest_version.status == 200
    retries: 3

  - name: set alertmanager_version
    set_fact:
      alertmanager_version: "{{ _latest_version.json['tag_name'] | regex_replace('^v', '') }}"

- block:
  - name: determine installed version
    command: "{{ alertmanager_bin_path }}/alertmanager --version"
    register: _installed_version_string
    changed_when: false

  - name: set alertmanager_local_version
    set_fact:
      alertmanager_local_version: "{{ _installed_version_string.stdout | regex_search(alertmanager_version_regex, '\\1') | first }}"
  when: alertmanager_installed

- name: set alertmanager_local_version to 0
  set_fact:
    alertmanager_local_version: "0"
  when: not alertmanager_installed

- block:
  - name: get checksums
    set_fact:
      _checksums: "{{ lookup('url', alertmanager_checksum_url, wantlist=True) }}"

  - name: set alertmanager_checksum
    set_fact:
      alertmanager_checksum: "sha256:{{ item.split(' ') | first }}"
    loop: "{{ _checksums }}"
    when: "alertmanager_release_file in item"
