---
- name: Configure netplan
  copy:
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: '0644'
    content: "{{ network_netplan_config | to_nice_yaml }}"
  notify: netplan apply
