---
- name: Remove default netplan configuration
  ansible.builtin.file:
    path: "{{ network_netplan_default_config_path }}"
    state: "{{ network_netplan_default_config_state | default('absent') }}"
    owner: root
    group: root
    mode: '0400'
  notify: netplan apply

- name: Configure netplan
  ansible.builtin.copy:
    dest: "{{ network_netplan_config_path }}"
    content: "{{ network_netplan | to_nice_yaml }}"
    owner: root
    group: root
    mode: '0400'
  notify: netplan apply
