---
- name: "download gitea {{ gitea_version }}"
  get_url:
    url: "{{ gitea_url }}"
    checksum: "{{ gitea_checksum }}"
    dest: "{{ gitea_path }}"
    owner: root
    group: root
    mode: 0755
  notify:
    - restart gitea
  retries: 3
  when: gitea_version != gitea_local_version
