- name: configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/gitea
    owner: root
    group: root
    mode: 0644
  notify: reload nginx

- name: activate site
  file:
    src: /etc/nginx/sites-available/gitea
    dest: /etc/nginx/sites-enabled/gitea
    owner: root
    group: root
    state: link
  notify: reload nginx
