---
loki_go_arch_map:
  i386: '386'
  x86_64: 'amd64'

loki_go_arch: "{{ loki_go_arch_map[ansible_architecture] | default('amd64') }}"

loki_service_name: loki.service
loki_service_enabled: true
loki_service_state: started

loki_version_regex: ^loki, version ([\d.]+)

loki_github_project_url: https://github.com/grafana/loki
loki_release_file: "loki-{{ ansible_system | lower }}-{{ loki_go_arch }}.zip"
loki_release_url: "{{ loki_github_project_url }}/releases/download/v{{ loki_version }}/{{ loki_release_file }}"
loki_checksum_url: "{{ loki_github_project_url }}/releases/download/v{{ loki_version }}/SHA256SUMS"
loki_download_path: "/tmp/{{ loki_release_file }}"
loki_unarchive_dest_path: /tmp
loki_extracted_path: "{{ loki_download_path | replace('.zip', '') }}"

loki_user: loki
loki_user_state: present
loki_user_shell: /usr/sbin/nologin

loki_group: loki
loki_group_state: "{{ loki_user_state | default('present') }}"

loki_var_path: /var/lib/loki
loki_var_owner: "{{ loki_user }}"
loki_var_group: "{{ loki_group }}"
loki_var_mode: "0700"

loki_etc_path: /etc/loki
loki_etc_owner: "{{ loki_user }}"
loki_etc_group: "{{ loki_group }}"
loki_etc_mode: "0755"

loki_config_path: "{{ loki_etc_path }}/config.yaml"

loki_bin_path: /usr/local/bin

loki_auth_enabled: false

loki_server:
  http_listen_port: 3100
  grpc_listen_port: 9096

loki_common:
  instance_addr: 127.0.0.1
  path_prefix: "{{ loki_var_path }}"
  storage:
    filesystem:
      chunks_directory: "{{ loki_var_path }}/chunks"
      rules_directory: "{{ loki_var_path }}/rules"
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

loki_query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

# loki_storage_config:
#   {}

loki_schema_config:
  configs:
  - from: 2020-10-24
    store: boltdb-shipper
    object_store: gcs
    schema: v11
    index:
      prefix: index_
      period: 24h

loki_ruler:
  alertmanager_url: http://localhost:9093

# loki_query_scheduler:
#   {}

# loki_querier:
#   {}

# loki_compactor:
#   {}

loki_limits_config:
  retention_period: 744h