---
restic_service_name: restic.service
restic_service_state: started
restic_service_enabled: yes

restic_arch: amd64
restic_version: 0.14.0
restic_url: "https://github.com/restic/restic/releases/download/v{{ restic_version }}/restic_{{ restic_version }}_linux_{{ restic_arch }}.bz2"
restic_checksum: sha256:c8da7350dc334cd5eaf13b2c9d6e689d51e7377ba1784cc6d65977bd44ee1165
restic_bin_path: /usr/local/bin
restic_etc_path: /etc/restic
restic_path: "{{ restic_bin_path }}/restic"
restic_self_update: true

restic_global_exclude:
  - /dev
  - /media
  - /mnt
  - /proc
  - /run
  - /sys
  - /tmp
  - /var/tmp
  - /var/lib/lxcfs/cgroup

restic_repos: []
restic_jobs: []
