---
restic_go_arch_map:
  i386: '386'
  x86_64: 'amd64'


restic_go_arch: "{{ restic_go_arch_map[ansible_architecture] | default('amd64') }}"

restic_version_regex: ^restic ([\d.]+)

restic_checksum_algo: sha256
restic_github_rel_path: restic/restic
restic_github_project_url: "https://github.com/{{ restic_github_rel_path }}"
restic_release_file: "restic_{{ restic_version }}_{{ ansible_system | lower }}_{{ restic_go_arch }}.bz2"
restic_release_url: "{{ restic_github_project_url }}/releases/download/v{{ restic_version }}/{{ restic_release_file }}"
restic_checksum_url: "{{ restic_github_project_url }}/releases/download/v{{ restic_version }}/{{ restic_checksum_algo | upper }}SUMS"
restic_download_path: "/tmp/{{ restic_release_file }}"
restic_unarchive_dest_path: /tmp
restic_extracted_path: "{{ restic_download_path | replace('.bz2', '') }}"
restic_binaries:
 - restic

# restic_arch: amd64
# restic_version: 0.15.2
# restic_url: "https://github.com/restic/restic/releases/download/v{{ restic_version }}/restic_{{ restic_version }}_linux_{{ restic_arch }}.bz2"
# restic_checksum: sha256:c8da7350dc334cd5eaf13b2c9d6e689d51e7377ba1784cc6d65977bd44ee1165
# restic_bin_path: /usr/local/bin
# restic_etc_path: /etc/restic
# restic_path: "{{ restic_bin_path }}/restic"
# restic_self_update: true

restic_bin_path: /usr/local/bin
restic_etc_path: /etc/restic
restic_path: "{{ restic_bin_path }}/restic"
restic_self_update: true

restic_global_exclude:
  - /dev
  - /media
  - /mnt
  - /proc
  - /run
  - /sys
  - /tmp
  - /var/tmp
  - /var/lib/lxcfs/cgroup

restic_repos: []
restic_jobs: []

restic_tidy_enabled: false
