---
- name: determine if installed
  stat:
    path: "{{ node_exporter_bin_path }}/node_exporter"
  register: st

- name: set node_exporter_installed
  set_fact:
    node_exporter_installed: "{{ st.stat.exists | bool }}"

- block:
  - name: determine latest version
    uri:
      url: https://api.github.com/repos/prometheus/node_exporter/releases/latest
      return_content: true
      body_format: json
    register: _latest_version
    until: _latest_version.status == 200
    retries: 3

  - name: set node_exporter_version
    set_fact:
      node_exporter_version: "{{ _latest_version.json['tag_name'] | regex_replace('^v', '') }}"

- block:
  - name: determine installed version
    command: "{{ node_exporter_bin_path }}/node_exporter --version"
    register: _installed_version_string
    changed_when: false

  - name: set node_exporter_local_version
    set_fact:
      node_exporter_local_version: "{{ _installed_version_string.stdout | regex_search(node_exporter_version_regex, '\\1') | first }}"
  when: node_exporter_installed

- name: set node_exporter_local_version to 0
  set_fact:
    node_exporter_local_version: "0"
  when: not node_exporter_installed

- block:
  - name: get checksums
    set_fact:
      _checksums: "{{ lookup('url', node_exporter_checksum_url, wantlist=True) }}"

  - name: set node_exporter_checksum
    set_fact:
      node_exporter_checksum: "sha256:{{ item.split(' ') | first }}"
    loop: "{{ _checksums }}"
    when: "node_exporter_release_file in item"
