---
- name: reload rabbitmq
  service:
    name: "{{ rabbitmq_service_name }}"
    state: reloaded
  when: rabbitmq_service_enabled

- name: restart rabbitmq
  service:
    name: "{{ rabbitmq_service_name }}"
    state: restarted
  when: rabbitmq_service_enabled
