---
vm_guest_qemu_agent_package_state: present
vm_guest_qemu_agent_service_state: started
vm_guest_qemu_agent_service_enabled: yes

vm_guest_spice_agent_package_state: present
vm_guest_spice_agent_service_state: started
vm_guest_spice_agent_service_enabled: yes
