---
grafana_package_version:
grafana_package_name: "grafana{{ grafana_package_version }}"
grafana_package_state: present

grafana_service_name: grafana-server.service
grafana_service_state: started
grafana_service_enabled: true

grafana_etc_path: /etc/grafana
grafana_var_path: /var/lib/grafana
grafana_dashboard_path: "{{ grafana_var_path }}/dashboards"
grafana_config_path: "{{ grafana_etc_path }}/grafana.ini"
grafana_provisioning_path: /etc/grafana/provisioning

grafana_domain: "stats.{{ ansible_domain }}"
grafana_port: 3002
grafana_user: grafana
grafana_group: grafana

grafana_config:
  server:
    domain: "{{ grafana_domain }}"
    root_url: "https://{{ grafana_domain }}"
    http_addr: localhost
    http_port: "{{ grafana_port }}"

grafana_ssl_enabled: true
grafana_ssl_certificate: "/etc/letsencrypt/live/{{ grafana_domain }}/fullchain.pem"
grafana_ssl_certificate_key: "/etc/letsencrypt/live/{{ grafana_domain }}/privkey.pem"
# grafana_ssl_dhparam: "/etc/letsencrypt/ssl-dhparams.pem"


grafana_user_dashboard_path: files/grafana/dashboards/

grafana_datasources:
  {}

grafana_dashboards:
  {}

grafana_dashboard_files:
  []
