---
- name: gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"

- name: run os specific tasks
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yaml"

- name: set hostname
  hostname:
    name: "{{ hostname | default(inventory_hostname) }}"

- name: configure system timezone
  timezone:
    name: "{{ timezone }}"
  notify: restart cron

# vim:ft=yaml.ansible:
