---
- name: gather OS specific variables
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
        - "{{ ansible_distribution }}.yaml"
        - "{{ ansible_os_family }}.yaml"
        - "default.yaml"
      paths:
        - vars

- name: run os specific tasks
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
        - "{{ ansible_distribution }}.yaml"
        - "{{ ansible_os_family }}.yaml"
        - "default.yaml"
      paths:
        - tasks

- name: set hostname
  ansible.builtin.hostname:
    name: "{{ common_hostname | default(inventory_hostname) }}"

- name: configure system timezone
  ansible.builtin.timezone:
    name: "{{ common_timezone | default('Etc/UTC') }}"
  notify: restart cron

- name: configure system locale
  ansible.builtin.command:
    cmd: "localectl set-locale {{ common_locale | default('C.UTF-8') }}"
  when: ansible_facts.env.LANG != (common_locale | default('C.UTF-8'))

# vim:ft=yaml.ansible:
