---
- name: grafana daemon-reload
  ansible.builtin.systemd:
    name: "{{ grafana_service_name }}"
    daemon_reload: true
    state: restarted

- name: restart grafana
  ansible.builtin.service:
    name: "{{ grafana_service_name }}"
    state: restarted
