---
vm_guest_qemu_agent_package_name: qemu-guest-agent
vm_guest_qemu_agent_service_name: qemu-guest-agent

vm_guest_spice_agent_package_name: spice-vdagent
vm_guest_spice_agent_service_name: spice-vdagent
