---
- name: restart prometheus
  systemd:
    name: prometheus.service
    daemon_reload: true
    state: restarted

- name: reload prometheus
  service:
    name: prometheus.service
    state: reloaded
