---
grafana_package_version:
grafana_package_name: "grafana{{grafana_package_version}}"
grafana_package_state: present

grafana_service_name: grafana-server.service
grafana_service_state: started
grafana_service_enabled: true

grafana_etc_path: /etc/grafana
grafana_config_path: "{{ grafana_etc_path }}/grafana.ini"
grafana_provisioning_path: /etc/grafana/provisioning

grafana_domain: "stats.{{ ansible_domain }}"
grafana_port: 3002
grafana_user: grafana
grafana_group: grafana

grafana_config:
  server:
    domain: "{{ grafana_domain }}"
    root_url: "https://{{ grafana_domain }}"
    http_addr: localhost
    http_port: "{{ grafana_port }}"

grafana_ssl_enabled: true
grafana_ssl_certificate: "/var/lib/lego/certificates/{{ grafana_domain }}.crt"
grafana_ssl_certificate_key: "/var/lib/lego/certificates/{{ grafana_domain }}.key"

grafana_datasources:
  apiVersion: 1
  deleteDatasources:
    - name: influxdb
      orgId: 1
  datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://localhost:9090
      isDefault: true
      version: 1
    - name: Thanos
      type: prometheus
      access: proxy
      orgId: 1
      url: http://localhost:10913
      version: 1

grafana_dashboards:
  apiVersion: 1
  providers:
    - name: ansible
      folder: Built-in
      type: file
      options:
        path: /var/lib/grafana/dashboards

grafana_dashboard_files:
  - connectivity.json
  - home-networking.json
  - iptables.json
  - nginx.json
  - processes.json
  - switching.json
  - system.json
  - ups.json

firewall_ipset_influxdb:
  - 172.16.100.16
  - 10.255.0.17

telegraf_config_outputs:
  influxdb:
    urls:
      - http://localhost:8086
